from pathlib import Path

p=Path('src/game/client/components/menus_settings.cpp')
s=p.read_text(encoding='utf-8')
needle='''\t\t\tif(g_Config.m_BkwMinimalHud)\n\t\t\t{\n\t\t\t\tPageView.HSplitTop(8.0f, nullptr, &PageView);\n'''
preview=r'''\t\t\tif(g_Config.m_BkwMinimalHud)\n\t\t\t{\n\t\t\t\tPageView.HSplitTop(8.0f, nullptr, &PageView);\n\t\t\t\tCUIRect PreviewCard;\n\t\t\t\tPageView.HSplitTop(g_Config.m_BkwMinimalHudLayout ? 84.0f : 62.0f, &PreviewCard, &PageView);\n\t\t\t\tPreviewCard.Draw(ColorRGBA(0.055f, 0.06f, 0.075f, 0.55f), IGraphics::CORNER_ALL, 6.0f);\n\t\t\t\tCUIRect PreviewLabel, PreviewArea;\n\t\t\t\tPreviewCard.HSplitTop(20.0f, &PreviewLabel, &PreviewArea);\n\t\t\t\tPreviewLabel.Margin(8.0f, &PreviewLabel);\n\t\t\t\tUi()->DoLabel(&PreviewLabel, "Предпросмотр", 11.0f, TEXTALIGN_ML);\n\t\t\t\tPreviewArea.Margin(8.0f, &PreviewArea);\n\n\t\t\t\tconst float PreviewScale = std::clamp(g_Config.m_BkwMinimalHudScale / 100.0f, 0.75f, 1.25f);\n\t\t\t\tconst float FontSize = 6.5f * PreviewScale;\n\t\t\t\tconst float PadX = 6.0f * PreviewScale;\n\t\t\t\tconst float PadY = 4.0f * PreviewScale;\n\t\t\t\tconst float Alpha = std::clamp(g_Config.m_BkwMinimalHudAlpha / 100.0f, 0.4f, 0.8f);\n\t\t\t\tconst char *pLine1 = "144 FPS   38 ms   TEAM 3   SPD 12.4   CP 3";\n\t\t\t\tconst char *pLine2 = "TIME 01:24.38   PB -0.42";\n\t\t\t\tconst bool CompactPreview = g_Config.m_BkwMinimalHudLayout != 0;\n\t\t\t\tconst float W1 = TextRender()->TextWidth(FontSize, pLine1);\n\t\t\t\tconst float W2 = CompactPreview ? TextRender()->TextWidth(FontSize, pLine2) : 0.0f;\n\t\t\t\tconst float HudW = minimum(PreviewArea.w, maximum(W1, W2) + PadX * 2.0f);\n\t\t\t\tconst float HudH = (CompactPreview ? FontSize * 2.0f + 2.0f * PreviewScale : FontSize) + PadY * 2.0f;\n\t\t\t\tconst float HudX = PreviewArea.x + (PreviewArea.w - HudW) / 2.0f;\n\t\t\t\tconst float HudY = PreviewArea.y + maximum(0.0f, (PreviewArea.h - HudH) / 2.0f);\n\t\t\t\tconst int Style = std::clamp(g_Config.m_BkwMinimalHudStyle, 0, 2);\n\t\t\t\tif(Style != 2)\n\t\t\t\t{\n\t\t\t\t\tconst ColorRGBA Bg = Style == 1 ? ColorRGBA(0.08f, 0.11f, 0.16f, Alpha * 0.72f) : ColorRGBA(0.03f, 0.03f, 0.03f, Alpha);\n\t\t\t\t\tGraphics()->DrawRect(HudX, HudY, HudW, HudH, Bg, IGraphics::CORNER_ALL, 4.5f * PreviewScale);\n\t\t\t\t}\n\t\t\t\tif(g_Config.m_BkwMinimalHudAccent)\n\t\t\t\t\tGraphics()->DrawRect(HudX, HudY, 1.5f * PreviewScale, HudH, ColorRGBA(0.35f, 0.72f, 1.0f, 0.95f), IGraphics::CORNER_L, 4.5f * PreviewScale);\n\t\t\t\tTextRender()->TextColor(0.94f, 0.96f, 1.0f, 1.0f);\n\t\t\t\tTextRender()->Text(HudX + PadX, HudY + PadY, FontSize, pLine1, HudW - PadX * 2.0f);\n\t\t\t\tif(CompactPreview)\n\t\t\t\t{\n\t\t\t\t\tTextRender()->TextColor(0.45f, 1.0f, 0.55f, 1.0f);\n\t\t\t\t\tTextRender()->Text(HudX + PadX, HudY + PadY + FontSize + 2.0f * PreviewScale, FontSize, pLine2, HudW - PadX * 2.0f);\n\t\t\t\t}\n\t\t\t\tTextRender()->TextColor(TextRender()->DefaultTextColor());\n\t\t\t\tPageView.HSplitTop(10.0f, nullptr, &PageView);\n'''
if '"Предпросмотр"' not in s[s.find('else if(s_BkwTab == BKW_TAB_HUD)'):s.find('else if(s_BkwTab == BKW_TAB_BACKGROUND)')]:
    assert needle in s
    s=s.replace(needle,preview,1)
p.write_text(s,encoding='utf-8')
